

SELECT * FROM STUDENTS;

SELECT * FROM COURSES;

SELECT * FROM STUDENT_COURSE;


SELECT s.NAME AS student_name, c.TITLE AS course_name
FROM STUDENT_COURSE sc
JOIN STUDENTS s ON sc.STUDENT_ID = s.id
JOIN COURSES c ON sc.COURSE_ID = c.id
ORDER BY s.NAME;