spring.application.name=EmployeeRestAPI

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/dborclpdb
spring.datasource.username=hr
spring.datasource.password=hr
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true